<?php
// auto-generated by sfRoutingConfigHandler
// date: 2012/04/23 12:21:53
$routes = sfRouting::getInstance();
$routes->setRoutes(
array (
  'homepage' => 
  array (
    0 => '/',
    1 => '/^[\\/]*$/',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'default',
      'action' => 'index',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'default_index' => 
  array (
    0 => '/:module',
    1 => '#^(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'module',
    ),
    3 => 
    array (
      'module' => 1,
    ),
    4 => 
    array (
      'action' => 'index',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'default' => 
  array (
    0 => '/:module/:action/*',
    1 => '#^(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?(?:\\/(.*))?$#',
    2 => 
    array (
      0 => 'module',
      1 => 'action',
    ),
    3 => 
    array (
      'module' => 1,
      'action' => 1,
    ),
    4 => 
    array (
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'sf_guard_signin' => 
  array (
    0 => '/login',
    1 => '#^/login$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'sfGuardAuth',
      'action' => 'signin',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'sf_guard_signout' => 
  array (
    0 => '/logout',
    1 => '#^/logout$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'sfGuardAuth',
      'action' => 'signout',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'sf_guard_password' => 
  array (
    0 => '/request_password',
    1 => '#^/request_password$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'sfGuardAuth',
      'action' => 'password',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
)
);
