<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/04/23 12:24:33
$this->security = array (
  'index' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
        1 => 'Comercial',
        2 => 'Almacen',
      ),
    ),
  ),
  'administrarpedidos' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
        1 => 'Comercial',
        2 => 'Almacen',
      ),
    ),
  ),
  'agregararticulopedido' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
        1 => 'Comercial',
        2 => 'Almacen',
      ),
    ),
  ),
  'agregarpedido' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
        1 => 'Comercial',
        2 => 'Almacen',
      ),
    ),
  ),
  'bajarcantidadarticulopedido' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
        1 => 'Comercial',
        2 => 'Almacen',
      ),
    ),
  ),
  'borrararticulopedido' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
        1 => 'Comercial',
        2 => 'Almacen',
      ),
    ),
  ),
  'borrarpedido' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
        1 => 'Comercial',
        2 => 'Almacen',
      ),
    ),
  ),
  'buscararticulopedido' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
        1 => 'Comercial',
        2 => 'Almacen',
      ),
    ),
  ),
  'buscarproveedorarticulo' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
        1 => 'Comercial',
        2 => 'Almacen',
      ),
    ),
  ),
  'comprobarpedidocompleto' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
        1 => 'Comercial',
        2 => 'Almacen',
      ),
    ),
  ),
  'confirmarpedidorecibido' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
        1 => 'Comercial',
        2 => 'Almacen',
      ),
    ),
  ),
  'confirmarpedido' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
        1 => 'Comercial',
        2 => 'Almacen',
      ),
    ),
  ),
  'editarpedido' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
        1 => 'Comercial',
        2 => 'Almacen',
      ),
    ),
  ),
  'generarpedido' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
        1 => 'Comercial',
        2 => 'Almacen',
      ),
    ),
  ),
  'pedidoscompletos' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
        1 => 'Comercial',
        2 => 'Almacen',
      ),
    ),
  ),
  'pedidosenproceso' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
        1 => 'Comercial',
        2 => 'Almacen',
      ),
    ),
  ),
  'pedidospendientes' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
        1 => 'Comercial',
        2 => 'Almacen',
      ),
    ),
  ),
  'pedidosprocesados' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
        1 => 'Comercial',
        2 => 'Almacen',
      ),
    ),
  ),
  'pedidosrecibidos' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
        1 => 'Comercial',
        2 => 'Almacen',
      ),
    ),
  ),
  'subircantidadarticulopedido' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
        1 => 'Comercial',
        2 => 'Almacen',
      ),
    ),
  ),
  'verpedidocompleto' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
        1 => 'Comercial',
        2 => 'Almacen',
      ),
    ),
  ),
  'verpedido' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
        1 => 'Comercial',
        2 => 'Almacen',
      ),
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
