<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/04/23 12:21:54
$this->security = array (
  'index' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'Administrador',
        1 => 'Comercial',
        2 => 'Almacen',
      ),
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
