# default values
all:
  sf_guard_plugin:
    profile_class:      SfGuardUserProfile
    profile_field_name: user_id
    success_signin_url:      default/index 
    success_signout_url:     default/index