default:
  http_metas:
    content-type: text/html

  metas:
    title:        SGUM
    robots:       noindex, nofollow
    description:  Sistema de Gestión de Ubicaciones
    keywords:     symfony, pfc, sgum, ubicaciones,
    language:     es

  stylesheets:    [main]

  javascripts:    [jquery.min.js, jquery.js]

  has_layout:     on
  layout:         layout
