<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/04/23 12:23:05

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'mysql://lacuevadsgum:qV86LniN@mysql51-59.bdb/lacuevadsgum',
), 'propel');
$this->databases['propel'] = $database;
