<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/04/23 12:23:05
sfConfig::add(array(
  'sf_i18n_default_culture' => 'es',
  'sf_i18n_source' => 'XLIFF',
  'sf_i18n_debug' => false,
  'sf_i18n_cache' => true,
  'sf_i18n_untranslated_prefix' => '[T]',
  'sf_i18n_untranslated_suffix' => '[/T]',
));
