<?php
// auto-generated by sfValidatorConfigHandler
// date: 2012/04/23 12:23:05

if ($_SERVER['REQUEST_METHOD'] == 'GET')
{
  $validators = array();
  $context->getRequest()->setAttribute('fillin', array (
  'enabled' => true,
), 'symfony/filter');
}
else if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
  $validators = array();
  $validators['sfStringValidator_nombre'] = new sfStringValidator();
  $validators['sfStringValidator_nombre']->initialize($context, array (
  'min' => 3,
  'min_error' => 'Debe contener al menos 3 caracteres.',
));
  $validators['sfRegexValidator_id_familia'] = new sfRegexValidator();
  $validators['sfRegexValidator_id_familia']->initialize($context, array (
  'match' => false,
  'match_error' => 'Debe asignar una familia al artículo.',
  'pattern' => '/^0$/',
));
  $validatorManager->registerName('nombre', 1, 'El campo nombre no puede estar vacio.', null, null, false);
  $validatorManager->registerValidator('nombre', $validators['sfStringValidator_nombre'], null);
  $validatorManager->registerName('id_familia', 0, 'Required', null, null, false);
  $validatorManager->registerValidator('id_familia', $validators['sfRegexValidator_id_familia'], null);
  $context->getRequest()->setAttribute('fillin', array (
  'enabled' => true,
), 'symfony/filter');
}
